# -*- coding: utf-8 -*-


#AVISO: Os codigos de autoria humana estão a partir da linha 1438




# Form implementation generated from reading ui file 'Tela.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from libSTC import tabela_fluidos, Nome_fluidos, ConverterTemperatura
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(847, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(237, 237, 237);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(2, 1, 1, 1)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.buttons_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttons_frame.sizePolicy().hasHeightForWidth())
        self.buttons_frame.setSizePolicy(sizePolicy)
        self.buttons_frame.setMinimumSize(QtCore.QSize(110, 0))
        self.buttons_frame.setSizeIncrement(QtCore.QSize(1, 1))
        self.buttons_frame.setAcceptDrops(False)
        self.buttons_frame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buttons_frame.setLineWidth(0)
        self.buttons_frame.setMidLineWidth(1)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.fluido2_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fluido2_btn.sizePolicy().hasHeightForWidth())
        self.fluido2_btn.setSizePolicy(sizePolicy)
        self.fluido2_btn.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fluido2_btn.setFont(font)
        self.fluido2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fluido2_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fluido2_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.fluido2_btn.setFlat(True)
        self.fluido2_btn.setObjectName("fluido2_btn")
        self.gridLayout.addWidget(self.fluido2_btn, 2, 0, 1, 1)
        self.fluido1_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fluido1_btn.sizePolicy().hasHeightForWidth())
        self.fluido1_btn.setSizePolicy(sizePolicy)
        self.fluido1_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.fluido1_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fluido1_btn.setFont(font)
        self.fluido1_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fluido1_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fluido1_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fluido1_btn.setAutoFillBackground(False)
        self.fluido1_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.fluido1_btn.setCheckable(False)
        self.fluido1_btn.setChecked(False)
        self.fluido1_btn.setAutoRepeat(False)
        self.fluido1_btn.setDefault(False)
        self.fluido1_btn.setFlat(True)
        self.fluido1_btn.setObjectName("fluido1_btn")
        self.gridLayout.addWidget(self.fluido1_btn, 1, 0, 1, 1)
        self.resultados_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.resultados_btn.sizePolicy().hasHeightForWidth())
        self.resultados_btn.setSizePolicy(sizePolicy)
        self.resultados_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.resultados_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resultados_btn.setFont(font)
        self.resultados_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resultados_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.resultados_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.resultados_btn.setFlat(True)
        self.resultados_btn.setObjectName("resultados_btn")
        self.gridLayout.addWidget(self.resultados_btn, 4, 0, 1, 1)
        self.trocador_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.trocador_btn.sizePolicy().hasHeightForWidth())
        self.trocador_btn.setSizePolicy(sizePolicy)
        self.trocador_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.trocador_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.trocador_btn.setFont(font)
        self.trocador_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trocador_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.trocador_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.trocador_btn.setFlat(True)
        self.trocador_btn.setObjectName("trocador_btn")
        self.gridLayout.addWidget(self.trocador_btn, 3, 0, 1, 1)
        self.projeto_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.projeto_btn.sizePolicy().hasHeightForWidth())
        self.projeto_btn.setSizePolicy(sizePolicy)
        self.projeto_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.projeto_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.projeto_btn.setFont(font)
        self.projeto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.projeto_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.projeto_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.projeto_btn.setAutoFillBackground(False)
        self.projeto_btn.setStyleSheet("background-color:rgb(217, 217, 217);\n"
"color: rgb(48, 143, 123);")
        self.projeto_btn.setCheckable(False)
        self.projeto_btn.setChecked(False)
        self.projeto_btn.setAutoRepeat(False)
        self.projeto_btn.setDefault(False)
        self.projeto_btn.setFlat(True)
        self.projeto_btn.setObjectName("projeto_btn")
        self.gridLayout.addWidget(self.projeto_btn, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_4.addWidget(self.buttons_frame, 1, 0, 1, 1)
        self.toolbar = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolbar.sizePolicy().hasHeightForWidth())
        self.toolbar.setSizePolicy(sizePolicy)
        self.toolbar.setMinimumSize(QtCore.QSize(0, 33))
        self.toolbar.setMaximumSize(QtCore.QSize(16777215, 61))
        self.toolbar.setStyleSheet("background-color: rgb(48, 143, 123);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.toolbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbar.setObjectName("toolbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.newFile_btn = QtWidgets.QPushButton(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newFile_btn.sizePolicy().hasHeightForWidth())
        self.newFile_btn.setSizePolicy(sizePolicy)
        self.newFile_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.newFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.newFile_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.newFile_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.newFile_btn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/newFile_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.newFile_btn.setIcon(icon)
        self.newFile_btn.setIconSize(QtCore.QSize(42, 23))
        self.newFile_btn.setFlat(True)
        self.newFile_btn.setObjectName("newFile_btn")
        self.horizontalLayout.addWidget(self.newFile_btn)
        self.openFile_btn = QtWidgets.QPushButton(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.openFile_btn.sizePolicy().hasHeightForWidth())
        self.openFile_btn.setSizePolicy(sizePolicy)
        self.openFile_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.openFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.openFile_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.openFile_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.openFile_btn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/openFile_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.openFile_btn.setIcon(icon1)
        self.openFile_btn.setIconSize(QtCore.QSize(35, 23))
        self.openFile_btn.setFlat(True)
        self.openFile_btn.setObjectName("openFile_btn")
        self.horizontalLayout.addWidget(self.openFile_btn)
        self.saveFile_btn = QtWidgets.QPushButton(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveFile_btn.sizePolicy().hasHeightForWidth())
        self.saveFile_btn.setSizePolicy(sizePolicy)
        self.saveFile_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.saveFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveFile_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.saveFile_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.saveFile_btn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/save_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveFile_btn.setIcon(icon2)
        self.saveFile_btn.setIconSize(QtCore.QSize(26, 23))
        self.saveFile_btn.setDefault(False)
        self.saveFile_btn.setFlat(True)
        self.saveFile_btn.setObjectName("saveFile_btn")
        self.horizontalLayout.addWidget(self.saveFile_btn)
        self.saveAsFile_btn = QtWidgets.QPushButton(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveAsFile_btn.sizePolicy().hasHeightForWidth())
        self.saveAsFile_btn.setSizePolicy(sizePolicy)
        self.saveAsFile_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.saveAsFile_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveAsFile_btn.setToolTipDuration(-2)
        self.saveAsFile_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.saveAsFile_btn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("images/Save-as-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveAsFile_btn.setIcon(icon3)
        self.saveAsFile_btn.setIconSize(QtCore.QSize(23, 18))
        self.saveAsFile_btn.setFlat(True)
        self.saveAsFile_btn.setObjectName("saveAsFile_btn")
        self.horizontalLayout.addWidget(self.saveAsFile_btn)
        self.calculate_btn = QtWidgets.QPushButton(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calculate_btn.sizePolicy().hasHeightForWidth())
        self.calculate_btn.setSizePolicy(sizePolicy)
        self.calculate_btn.setMaximumSize(QtCore.QSize(40, 16777215))
        self.calculate_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.calculate_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.calculate_btn.setStyleSheet("color: rgb(0, 0, 0);")
        self.calculate_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("images/calculateIcon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calculate_btn.setIcon(icon4)
        self.calculate_btn.setIconSize(QtCore.QSize(31, 23))
        self.calculate_btn.setFlat(True)
        self.calculate_btn.setObjectName("calculate_btn")
        self.horizontalLayout.addWidget(self.calculate_btn)
        self.title_label = QtWidgets.QLabel(self.toolbar)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_label.sizePolicy().hasHeightForWidth())
        self.title_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.gridLayout_4.addWidget(self.toolbar, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("color: rgb(48, 143, 123);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 2, 1)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("background-color: rgb(243, 243, 243);\n"
"color: rgb(48, 143, 123);")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_4.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.window_frame = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.window_frame.sizePolicy().hasHeightForWidth())
        self.window_frame.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.window_frame.setFont(font)
        self.window_frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.window_frame.setToolTip("")
        self.window_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.window_frame.setLineWidth(5)
        self.window_frame.setObjectName("window_frame")
        self.projeto_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projeto_page.sizePolicy().hasHeightForWidth())
        self.projeto_page.setSizePolicy(sizePolicy)
        self.projeto_page.setObjectName("projeto_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.projeto_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 20)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titulo_frame = QtWidgets.QFrame(self.projeto_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_frame.sizePolicy().hasHeightForWidth())
        self.titulo_frame.setSizePolicy(sizePolicy)
        self.titulo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titulo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo_frame.setObjectName("titulo_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.titulo_frame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTitle_label = QtWidgets.QLabel(self.titulo_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTitle_label.sizePolicy().hasHeightForWidth())
        self.mainTitle_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(70)
        self.mainTitle_label.setFont(font)
        self.mainTitle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mainTitle_label.setObjectName("mainTitle_label")
        self.verticalLayout.addWidget(self.mainTitle_label)
        self.label_17 = QtWidgets.QLabel(self.titulo_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(48, 48, 48);")
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.verticalLayout_5.addWidget(self.titulo_frame)
        spacerItem = QtWidgets.QSpacerItem(20, 53, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        self.verticalLayout_5.addItem(spacerItem)
        self.projeto_frame = QtWidgets.QFrame(self.projeto_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projeto_frame.sizePolicy().hasHeightForWidth())
        self.projeto_frame.setSizePolicy(sizePolicy)
        self.projeto_frame.setStyleSheet("")
        self.projeto_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projeto_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.projeto_frame.setObjectName("projeto_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.projeto_frame)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.projeto_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(166, 0))
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setFrameShape(QtWidgets.QFrame.Box)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 132, 81))
        self.page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.page)
        self.radioButton.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_4.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.page)
        self.radioButton_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_3.setCheckable(False)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.page)
        self.radioButton_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.radioButton_2.setCheckable(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 164, 69))
        self.page_2.setObjectName("page_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.abrirProjeto_btn = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.abrirProjeto_btn.sizePolicy().hasHeightForWidth())
        self.abrirProjeto_btn.setSizePolicy(sizePolicy)
        self.abrirProjeto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.abrirProjeto_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.abrirProjeto_btn.setFlat(True)
        self.abrirProjeto_btn.setObjectName("abrirProjeto_btn")
        self.verticalLayout_3.addWidget(self.abrirProjeto_btn)
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        self.verticalLayout_5.addWidget(self.projeto_frame)
        self.label_34 = QtWidgets.QLabel(self.projeto_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet("color: rgb(153, 153, 153);")
        self.label_34.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_5.addWidget(self.label_34)
        self.window_frame.addWidget(self.projeto_page)
        self.fluido1_page = QtWidgets.QWidget()
        self.fluido1_page.setObjectName("fluido1_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fluido1_page)
        self.gridLayout_2.setContentsMargins(40, 9, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.f1Fluids_combobox = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1Fluids_combobox.sizePolicy().hasHeightForWidth())
        self.f1Fluids_combobox.setSizePolicy(sizePolicy)
        self.f1Fluids_combobox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.f1Fluids_combobox.setFont(font)
        self.f1Fluids_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f1Fluids_combobox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f1Fluids_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f1Fluids_combobox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.f1Fluids_combobox.setFrame(False)
        self.f1Fluids_combobox.setModelColumn(0)
        self.f1Fluids_combobox.setObjectName("f1Fluids_combobox")
        self.f1Fluids_combobox.addItem("")
        self.f1Fluids_combobox.addItem("")
        self.f1Fluids_combobox.addItem("")
        self.f1Fluids_combobox.addItem("")
        self.f1Fluids_combobox.addItem("")
        self.gridLayout_2.addWidget(self.f1Fluids_combobox, 19, 0, 1, 2)
        self.f1Fluids_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.f1Fluids_label.sizePolicy().hasHeightForWidth())
        self.f1Fluids_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.f1Fluids_label.setFont(font)
        self.f1Fluids_label.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Fluids_label.setObjectName("f1Fluids_label")
        self.gridLayout_2.addWidget(self.f1Fluids_label, 18, 0, 1, 2)
        self.f1T1_entry = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1T1_entry.sizePolicy().hasHeightForWidth())
        self.f1T1_entry.setSizePolicy(sizePolicy)
        self.f1T1_entry.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1T1_entry.setFont(font)
        self.f1T1_entry.setToolTip("")
        self.f1T1_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1T1_entry.setFrame(False)
        self.f1T1_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f1T1_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1T1_entry.setMinimum(-99999.0)
        self.f1T1_entry.setMaximum(99999.0)
        self.f1T1_entry.setObjectName("f1T1_entry")
        self.gridLayout_2.addWidget(self.f1T1_entry, 2, 0, 1, 1)
        self.f1T1Unit_comboBox = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1T1Unit_comboBox.sizePolicy().hasHeightForWidth())
        self.f1T1Unit_comboBox.setSizePolicy(sizePolicy)
        self.f1T1Unit_comboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.f1T1Unit_comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1T1Unit_comboBox.setFont(font)
        self.f1T1Unit_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f1T1Unit_comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f1T1Unit_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f1T1Unit_comboBox.setFrame(False)
        self.f1T1Unit_comboBox.setModelColumn(0)
        self.f1T1Unit_comboBox.setObjectName("f1T1Unit_comboBox")
        self.f1T1Unit_comboBox.addItem("")
        self.f1T1Unit_comboBox.addItem("")
        self.f1T1Unit_comboBox.addItem("")
        self.f1T1Unit_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.f1T1Unit_comboBox, 2, 1, 1, 1)
        self.f1Flow_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1Flow_label.sizePolicy().hasHeightForWidth())
        self.f1Flow_label.setSizePolicy(sizePolicy)
        self.f1Flow_label.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1Flow_label.setFont(font)
        self.f1Flow_label.setObjectName("f1Flow_label")
        self.gridLayout_2.addWidget(self.f1Flow_label, 5, 0, 1, 1)
        self.f1Flow_entry = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1Flow_entry.sizePolicy().hasHeightForWidth())
        self.f1Flow_entry.setSizePolicy(sizePolicy)
        self.f1Flow_entry.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1Flow_entry.setFont(font)
        self.f1Flow_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1Flow_entry.setFrame(False)
        self.f1Flow_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Flow_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1Flow_entry.setMaximum(99999.0)
        self.f1Flow_entry.setObjectName("f1Flow_entry")
        self.gridLayout_2.addWidget(self.f1Flow_entry, 6, 0, 1, 1)
        self.f1T2_entry = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1T2_entry.sizePolicy().hasHeightForWidth())
        self.f1T2_entry.setSizePolicy(sizePolicy)
        self.f1T2_entry.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1T2_entry.setFont(font)
        self.f1T2_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1T2_entry.setFrame(False)
        self.f1T2_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f1T2_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1T2_entry.setMinimum(-9999.0)
        self.f1T2_entry.setMaximum(99999.0)
        self.f1T2_entry.setObjectName("f1T2_entry")
        self.gridLayout_2.addWidget(self.f1T2_entry, 4, 0, 1, 1)
        self.f1Mi_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.f1Mi_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1Mi_spinbox.setFont(font)
        self.f1Mi_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1Mi_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Mi_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1Mi_spinbox.setMinimum(0.0)
        self.f1Mi_spinbox.setMaximum(999999.0)
        self.f1Mi_spinbox.setObjectName("f1Mi_spinbox")
        self.gridLayout_2.addWidget(self.f1Mi_spinbox, 19, 4, 1, 1)
        self.f1R_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.f1R_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1R_spinbox.setFont(font)
        self.f1R_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1R_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.f1R_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1R_spinbox.setMinimum(0.0)
        self.f1R_spinbox.setMaximum(999999.0)
        self.f1R_spinbox.setObjectName("f1R_spinbox")
        self.gridLayout_2.addWidget(self.f1R_spinbox, 21, 4, 1, 1)
        self.f1T1_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1T1_label.sizePolicy().hasHeightForWidth())
        self.f1T1_label.setSizePolicy(sizePolicy)
        self.f1T1_label.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1T1_label.setFont(font)
        self.f1T1_label.setObjectName("f1T1_label")
        self.gridLayout_2.addWidget(self.f1T1_label, 1, 0, 1, 2)
        self.f1R_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1R_label.sizePolicy().hasHeightForWidth())
        self.f1R_label.setSizePolicy(sizePolicy)
        self.f1R_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1R_label.setFont(font)
        self.f1R_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1R_label.setObjectName("f1R_label")
        self.gridLayout_2.addWidget(self.f1R_label, 21, 3, 1, 1)
        self.f1Cp_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1Cp_label.sizePolicy().hasHeightForWidth())
        self.f1Cp_label.setSizePolicy(sizePolicy)
        self.f1Cp_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1Cp_label.setFont(font)
        self.f1Cp_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1Cp_label.setObjectName("f1Cp_label")
        self.gridLayout_2.addWidget(self.f1Cp_label, 17, 3, 1, 1)
        self.f1Mi_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1Mi_label.sizePolicy().hasHeightForWidth())
        self.f1Mi_label.setSizePolicy(sizePolicy)
        self.f1Mi_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1Mi_label.setFont(font)
        self.f1Mi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1Mi_label.setObjectName("f1Mi_label")
        self.gridLayout_2.addWidget(self.f1Mi_label, 19, 3, 1, 1)
        self.f1Image_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Image_label.setObjectName("f1Image_label")
        self.gridLayout_2.addWidget(self.f1Image_label, 1, 3, 5, 3)
        self.f1RUnit_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1RUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1RUnit_label.setFont(font)
        self.f1RUnit_label.setObjectName("f1RUnit_label")
        self.gridLayout_2.addWidget(self.f1RUnit_label, 21, 5, 1, 1)
        self.f1CpUnit_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1CpUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1CpUnit_label.setFont(font)
        self.f1CpUnit_label.setObjectName("f1CpUnit_label")
        self.gridLayout_2.addWidget(self.f1CpUnit_label, 17, 5, 1, 1)
        self.f1LineVertical = QtWidgets.QFrame(self.fluido1_page)
        self.f1LineVertical.setFrameShape(QtWidgets.QFrame.VLine)
        self.f1LineVertical.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f1LineVertical.setObjectName("f1LineVertical")
        self.gridLayout_2.addWidget(self.f1LineVertical, 17, 2, 5, 1)
        self.f1MiUnit_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1MiUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1MiUnit_label.setFont(font)
        self.f1MiUnit_label.setObjectName("f1MiUnit_label")
        self.gridLayout_2.addWidget(self.f1MiUnit_label, 19, 5, 1, 1)
        self.f1Rho_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1Rho_label.sizePolicy().hasHeightForWidth())
        self.f1Rho_label.setSizePolicy(sizePolicy)
        self.f1Rho_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1Rho_label.setFont(font)
        self.f1Rho_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1Rho_label.setObjectName("f1Rho_label")
        self.gridLayout_2.addWidget(self.f1Rho_label, 18, 3, 1, 1)
        self.f1RhoUnit_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1RhoUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1RhoUnit_label.setFont(font)
        self.f1RhoUnit_label.setObjectName("f1RhoUnit_label")
        self.gridLayout_2.addWidget(self.f1RhoUnit_label, 18, 5, 1, 1)
        self.f1Rho_spinBox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.f1Rho_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1Rho_spinBox.setFont(font)
        self.f1Rho_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1Rho_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Rho_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1Rho_spinBox.setMinimum(0.0)
        self.f1Rho_spinBox.setMaximum(999999.0)
        self.f1Rho_spinBox.setObjectName("f1Rho_spinBox")
        self.gridLayout_2.addWidget(self.f1Rho_spinBox, 18, 4, 1, 1)
        self.f1Cp_spinBox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.f1Cp_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1Cp_spinBox.setFont(font)
        self.f1Cp_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1Cp_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Cp_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1Cp_spinBox.setMinimum(0.0)
        self.f1Cp_spinBox.setMaximum(999999.0)
        self.f1Cp_spinBox.setObjectName("f1Cp_spinBox")
        self.gridLayout_2.addWidget(self.f1Cp_spinBox, 17, 4, 1, 1)
        self.f1KUnit_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1KUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f1KUnit_label.setFont(font)
        self.f1KUnit_label.setObjectName("f1KUnit_label")
        self.gridLayout_2.addWidget(self.f1KUnit_label, 20, 5, 1, 1)
        self.f1Kf_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.f1Kf_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1Kf_spinbox.setFont(font)
        self.f1Kf_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f1Kf_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.f1Kf_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f1Kf_spinbox.setMinimum(0.0)
        self.f1Kf_spinbox.setMaximum(999999.0)
        self.f1Kf_spinbox.setObjectName("f1Kf_spinbox")
        self.gridLayout_2.addWidget(self.f1Kf_spinbox, 20, 4, 1, 1)
        self.f1K_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1K_label.sizePolicy().hasHeightForWidth())
        self.f1K_label.setSizePolicy(sizePolicy)
        self.f1K_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1K_label.setFont(font)
        self.f1K_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1K_label.setObjectName("f1K_label")
        self.gridLayout_2.addWidget(self.f1K_label, 20, 3, 1, 1)
        self.f1FlowUnit_comboBox = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1FlowUnit_comboBox.sizePolicy().hasHeightForWidth())
        self.f1FlowUnit_comboBox.setSizePolicy(sizePolicy)
        self.f1FlowUnit_comboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.f1FlowUnit_comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1FlowUnit_comboBox.setFont(font)
        self.f1FlowUnit_comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f1FlowUnit_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f1FlowUnit_comboBox.setFrame(False)
        self.f1FlowUnit_comboBox.setModelColumn(0)
        self.f1FlowUnit_comboBox.setObjectName("f1FlowUnit_comboBox")
        self.f1FlowUnit_comboBox.addItem("")
        self.f1FlowUnit_comboBox.addItem("")
        self.f1FlowUnit_comboBox.addItem("")
        self.f1FlowUnit_comboBox.addItem("")
        self.gridLayout_2.addWidget(self.f1FlowUnit_comboBox, 6, 1, 1, 1)
        self.f1LineHorizontal = QtWidgets.QFrame(self.fluido1_page)
        self.f1LineHorizontal.setStyleSheet("")
        self.f1LineHorizontal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f1LineHorizontal.setLineWidth(1)
        self.f1LineHorizontal.setFrameShape(QtWidgets.QFrame.HLine)
        self.f1LineHorizontal.setObjectName("f1LineHorizontal")
        self.gridLayout_2.addWidget(self.f1LineHorizontal, 14, 0, 1, 6)
        self.f1T2_label = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f1T2_label.sizePolicy().hasHeightForWidth())
        self.f1T2_label.setSizePolicy(sizePolicy)
        self.f1T2_label.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f1T2_label.setFont(font)
        self.f1T2_label.setObjectName("f1T2_label")
        self.gridLayout_2.addWidget(self.f1T2_label, 3, 0, 1, 2)
        self.f1VerDados_btn = QtWidgets.QPushButton(self.fluido1_page)
        self.f1VerDados_btn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.f1VerDados_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f1VerDados_btn.setToolTip("")
        self.f1VerDados_btn.setDefault(True)
        self.f1VerDados_btn.setFlat(True)
        self.f1VerDados_btn.setObjectName("f1VerDados_btn")
        self.gridLayout_2.addWidget(self.f1VerDados_btn, 20, 1, 1, 1)
        self.f1TUnit_label = QtWidgets.QLabel(self.fluido1_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f1TUnit_label.setFont(font)
        self.f1TUnit_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.f1TUnit_label.setObjectName("f1TUnit_label")
        self.gridLayout_2.addWidget(self.f1TUnit_label, 4, 1, 1, 1)
        self.f1Warning_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1Warning_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.f1Warning_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.f1Warning_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1Warning_label.setObjectName("f1Warning_label")
        self.gridLayout_2.addWidget(self.f1Warning_label, 6, 3, 1, 1)
        self.f1Tm_label = QtWidgets.QLabel(self.fluido1_page)
        self.f1Tm_label.setMinimumSize(QtCore.QSize(155, 0))
        self.f1Tm_label.setMaximumSize(QtCore.QSize(155, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.f1Tm_label.setFont(font)
        self.f1Tm_label.setToolTip("")
        self.f1Tm_label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.f1Tm_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f1Tm_label.setObjectName("f1Tm_label")
        self.gridLayout_2.addWidget(self.f1Tm_label, 6, 4, 1, 1)
        self.window_frame.addWidget(self.fluido1_page)
        self.fluido2_page = QtWidgets.QWidget()
        self.fluido2_page.setObjectName("fluido2_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fluido2_page)
        self.gridLayout_5.setContentsMargins(40, -1, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.f2RUnit_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2RUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2RUnit_label.setFont(font)
        self.f2RUnit_label.setObjectName("f2RUnit_label")
        self.gridLayout_5.addWidget(self.f2RUnit_label, 12, 5, 1, 1)
        self.f2T2_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2T2_label.sizePolicy().hasHeightForWidth())
        self.f2T2_label.setSizePolicy(sizePolicy)
        self.f2T2_label.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2T2_label.setFont(font)
        self.f2T2_label.setObjectName("f2T2_label")
        self.gridLayout_5.addWidget(self.f2T2_label, 2, 0, 1, 2)
        self.f2KUnit_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2KUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2KUnit_label.setFont(font)
        self.f2KUnit_label.setObjectName("f2KUnit_label")
        self.gridLayout_5.addWidget(self.f2KUnit_label, 11, 5, 1, 1)
        self.f2T1_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2T1_label.sizePolicy().hasHeightForWidth())
        self.f2T1_label.setSizePolicy(sizePolicy)
        self.f2T1_label.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2T1_label.setFont(font)
        self.f2T1_label.setObjectName("f2T1_label")
        self.gridLayout_5.addWidget(self.f2T1_label, 0, 0, 1, 2)
        self.f2RhoUnit_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2RhoUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2RhoUnit_label.setFont(font)
        self.f2RhoUnit_label.setObjectName("f2RhoUnit_label")
        self.gridLayout_5.addWidget(self.f2RhoUnit_label, 9, 5, 1, 1)
        self.f2Mi_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2Mi_label.sizePolicy().hasHeightForWidth())
        self.f2Mi_label.setSizePolicy(sizePolicy)
        self.f2Mi_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2Mi_label.setFont(font)
        self.f2Mi_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2Mi_label.setObjectName("f2Mi_label")
        self.gridLayout_5.addWidget(self.f2Mi_label, 10, 3, 1, 1)
        self.f2K_spinBox = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.f2K_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2K_spinBox.setFont(font)
        self.f2K_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2K_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f2K_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2K_spinBox.setMinimum(0.0)
        self.f2K_spinBox.setMaximum(999999.0)
        self.f2K_spinBox.setObjectName("f2K_spinBox")
        self.gridLayout_5.addWidget(self.f2K_spinBox, 11, 4, 1, 1)
        self.f2Mi_spinBox = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.f2Mi_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2Mi_spinBox.setFont(font)
        self.f2Mi_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2Mi_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f2Mi_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2Mi_spinBox.setMinimum(0.0)
        self.f2Mi_spinBox.setMaximum(999999.0)
        self.f2Mi_spinBox.setObjectName("f2Mi_spinBox")
        self.gridLayout_5.addWidget(self.f2Mi_spinBox, 10, 4, 1, 1)
        self.f2MiUnit_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2MiUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2MiUnit_label.setFont(font)
        self.f2MiUnit_label.setObjectName("f2MiUnit_label")
        self.gridLayout_5.addWidget(self.f2MiUnit_label, 10, 5, 1, 1)
        self.f2R_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2R_label.sizePolicy().hasHeightForWidth())
        self.f2R_label.setSizePolicy(sizePolicy)
        self.f2R_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2R_label.setFont(font)
        self.f2R_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2R_label.setObjectName("f2R_label")
        self.gridLayout_5.addWidget(self.f2R_label, 12, 3, 1, 1)
        self.f2K_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2K_label.sizePolicy().hasHeightForWidth())
        self.f2K_label.setSizePolicy(sizePolicy)
        self.f2K_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2K_label.setFont(font)
        self.f2K_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2K_label.setObjectName("f2K_label")
        self.gridLayout_5.addWidget(self.f2K_label, 11, 3, 1, 1)
        self.f2R_spinBox = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.f2R_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2R_spinBox.setFont(font)
        self.f2R_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2R_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f2R_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2R_spinBox.setMinimum(0.0)
        self.f2R_spinBox.setMaximum(999999.0)
        self.f2R_spinBox.setObjectName("f2R_spinBox")
        self.gridLayout_5.addWidget(self.f2R_spinBox, 12, 4, 1, 1)
        self.f2Image_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2Image_label.setAlignment(QtCore.Qt.AlignCenter)
        self.f2Image_label.setObjectName("f2Image_label")
        self.gridLayout_5.addWidget(self.f2Image_label, 0, 3, 5, 3)
        self.f2Flow_entry = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2Flow_entry.sizePolicy().hasHeightForWidth())
        self.f2Flow_entry.setSizePolicy(sizePolicy)
        self.f2Flow_entry.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2Flow_entry.setFont(font)
        self.f2Flow_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2Flow_entry.setFrame(False)
        self.f2Flow_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f2Flow_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2Flow_entry.setMaximum(99999.0)
        self.f2Flow_entry.setObjectName("f2Flow_entry")
        self.gridLayout_5.addWidget(self.f2Flow_entry, 5, 0, 1, 1)
        self.f2T2_entry = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2T2_entry.sizePolicy().hasHeightForWidth())
        self.f2T2_entry.setSizePolicy(sizePolicy)
        self.f2T2_entry.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2T2_entry.setFont(font)
        self.f2T2_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2T2_entry.setFrame(False)
        self.f2T2_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f2T2_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2T2_entry.setMinimum(-99999.0)
        self.f2T2_entry.setMaximum(99999.0)
        self.f2T2_entry.setObjectName("f2T2_entry")
        self.gridLayout_5.addWidget(self.f2T2_entry, 3, 0, 1, 1)
        self.f2Flow_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2Flow_label.sizePolicy().hasHeightForWidth())
        self.f2Flow_label.setSizePolicy(sizePolicy)
        self.f2Flow_label.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2Flow_label.setFont(font)
        self.f2Flow_label.setObjectName("f2Flow_label")
        self.gridLayout_5.addWidget(self.f2Flow_label, 4, 0, 1, 1)
        self.f2T1Unit_comboBox = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2T1Unit_comboBox.sizePolicy().hasHeightForWidth())
        self.f2T1Unit_comboBox.setSizePolicy(sizePolicy)
        self.f2T1Unit_comboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.f2T1Unit_comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2T1Unit_comboBox.setFont(font)
        self.f2T1Unit_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f2T1Unit_comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f2T1Unit_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f2T1Unit_comboBox.setFrame(False)
        self.f2T1Unit_comboBox.setModelColumn(0)
        self.f2T1Unit_comboBox.setObjectName("f2T1Unit_comboBox")
        self.f2T1Unit_comboBox.addItem("")
        self.f2T1Unit_comboBox.addItem("")
        self.f2T1Unit_comboBox.addItem("")
        self.f2T1Unit_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.f2T1Unit_comboBox, 1, 1, 1, 1)
        self.f2FlowUnit_comboBox = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2FlowUnit_comboBox.sizePolicy().hasHeightForWidth())
        self.f2FlowUnit_comboBox.setSizePolicy(sizePolicy)
        self.f2FlowUnit_comboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.f2FlowUnit_comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2FlowUnit_comboBox.setFont(font)
        self.f2FlowUnit_comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f2FlowUnit_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f2FlowUnit_comboBox.setFrame(False)
        self.f2FlowUnit_comboBox.setModelColumn(0)
        self.f2FlowUnit_comboBox.setObjectName("f2FlowUnit_comboBox")
        self.f2FlowUnit_comboBox.addItem("")
        self.f2FlowUnit_comboBox.addItem("")
        self.f2FlowUnit_comboBox.addItem("")
        self.f2FlowUnit_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.f2FlowUnit_comboBox, 5, 1, 1, 1)
        self.f2Cp_spinBox = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.f2Cp_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2Cp_spinBox.setFont(font)
        self.f2Cp_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2Cp_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f2Cp_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2Cp_spinBox.setMinimum(0.0)
        self.f2Cp_spinBox.setMaximum(999999.0)
        self.f2Cp_spinBox.setObjectName("f2Cp_spinBox")
        self.gridLayout_5.addWidget(self.f2Cp_spinBox, 8, 4, 1, 1)
        self.f2LineVertical = QtWidgets.QFrame(self.fluido2_page)
        self.f2LineVertical.setFrameShape(QtWidgets.QFrame.VLine)
        self.f2LineVertical.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f2LineVertical.setObjectName("f2LineVertical")
        self.gridLayout_5.addWidget(self.f2LineVertical, 8, 2, 5, 1)
        self.f2Cp_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2Cp_label.sizePolicy().hasHeightForWidth())
        self.f2Cp_label.setSizePolicy(sizePolicy)
        self.f2Cp_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2Cp_label.setFont(font)
        self.f2Cp_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2Cp_label.setObjectName("f2Cp_label")
        self.gridLayout_5.addWidget(self.f2Cp_label, 8, 3, 1, 1)
        self.f2Rho_spinBox = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.f2Rho_spinBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2Rho_spinBox.setFont(font)
        self.f2Rho_spinBox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2Rho_spinBox.setAlignment(QtCore.Qt.AlignCenter)
        self.f2Rho_spinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2Rho_spinBox.setMinimum(0.0)
        self.f2Rho_spinBox.setMaximum(999999.0)
        self.f2Rho_spinBox.setObjectName("f2Rho_spinBox")
        self.gridLayout_5.addWidget(self.f2Rho_spinBox, 9, 4, 1, 1)
        self.f2CpUnit_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2CpUnit_label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.f2CpUnit_label.setFont(font)
        self.f2CpUnit_label.setObjectName("f2CpUnit_label")
        self.gridLayout_5.addWidget(self.f2CpUnit_label, 8, 5, 1, 1)
        self.f2Fluids_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.f2Fluids_label.sizePolicy().hasHeightForWidth())
        self.f2Fluids_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.f2Fluids_label.setFont(font)
        self.f2Fluids_label.setAlignment(QtCore.Qt.AlignCenter)
        self.f2Fluids_label.setObjectName("f2Fluids_label")
        self.gridLayout_5.addWidget(self.f2Fluids_label, 9, 0, 1, 2)
        self.f2T1_entry = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2T1_entry.sizePolicy().hasHeightForWidth())
        self.f2T1_entry.setSizePolicy(sizePolicy)
        self.f2T1_entry.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2T1_entry.setFont(font)
        self.f2T1_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.f2T1_entry.setFrame(False)
        self.f2T1_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.f2T1_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.f2T1_entry.setMinimum(-99999.0)
        self.f2T1_entry.setMaximum(99999.0)
        self.f2T1_entry.setObjectName("f2T1_entry")
        self.gridLayout_5.addWidget(self.f2T1_entry, 1, 0, 1, 1)
        self.f2Rho_label = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2Rho_label.sizePolicy().hasHeightForWidth())
        self.f2Rho_label.setSizePolicy(sizePolicy)
        self.f2Rho_label.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.f2Rho_label.setFont(font)
        self.f2Rho_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2Rho_label.setObjectName("f2Rho_label")
        self.gridLayout_5.addWidget(self.f2Rho_label, 9, 3, 1, 1)
        self.f2LineHorizontal = QtWidgets.QFrame(self.fluido2_page)
        self.f2LineHorizontal.setStyleSheet("")
        self.f2LineHorizontal.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.f2LineHorizontal.setLineWidth(1)
        self.f2LineHorizontal.setFrameShape(QtWidgets.QFrame.HLine)
        self.f2LineHorizontal.setObjectName("f2LineHorizontal")
        self.gridLayout_5.addWidget(self.f2LineHorizontal, 7, 0, 1, 6)
        self.f2Warning_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2Warning_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2Warning_label.setObjectName("f2Warning_label")
        self.gridLayout_5.addWidget(self.f2Warning_label, 5, 3, 1, 1)
        self.f2Tm_label = QtWidgets.QLabel(self.fluido2_page)
        self.f2Tm_label.setMinimumSize(QtCore.QSize(155, 0))
        self.f2Tm_label.setMaximumSize(QtCore.QSize(155, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(9)
        self.f2Tm_label.setFont(font)
        self.f2Tm_label.setToolTip("")
        self.f2Tm_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.f2Tm_label.setObjectName("f2Tm_label")
        self.gridLayout_5.addWidget(self.f2Tm_label, 5, 4, 1, 1)
        self.f2Fluids_comboBox = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f2Fluids_comboBox.sizePolicy().hasHeightForWidth())
        self.f2Fluids_comboBox.setSizePolicy(sizePolicy)
        self.f2Fluids_comboBox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.f2Fluids_comboBox.setFont(font)
        self.f2Fluids_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.f2Fluids_comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f2Fluids_comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f2Fluids_comboBox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.f2Fluids_comboBox.setFrame(False)
        self.f2Fluids_comboBox.setModelColumn(0)
        self.f2Fluids_comboBox.setObjectName("f2Fluids_comboBox")
        self.f2Fluids_comboBox.addItem("")
        self.f2Fluids_comboBox.addItem("")
        self.f2Fluids_comboBox.addItem("")
        self.f2Fluids_comboBox.addItem("")
        self.f2Fluids_comboBox.addItem("")
        self.gridLayout_5.addWidget(self.f2Fluids_comboBox, 10, 0, 1, 2)
        self.f2VerDados_btn = QtWidgets.QPushButton(self.fluido2_page)
        self.f2VerDados_btn.setMaximumSize(QtCore.QSize(70, 16777215))
        self.f2VerDados_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.f2VerDados_btn.setDefault(True)
        self.f2VerDados_btn.setFlat(True)
        self.f2VerDados_btn.setObjectName("f2VerDados_btn")
        self.gridLayout_5.addWidget(self.f2VerDados_btn, 11, 1, 1, 1)
        self.f2TUnit_label = QtWidgets.QLabel(self.fluido2_page)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.f2TUnit_label.setFont(font)
        self.f2TUnit_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.f2TUnit_label.setObjectName("f2TUnit_label")
        self.gridLayout_5.addWidget(self.f2TUnit_label, 3, 1, 1, 1)
        self.window_frame.addWidget(self.fluido2_page)
        self.trocador_page = QtWidgets.QWidget()
        self.trocador_page.setObjectName("trocador_page")
        self.label_19 = QtWidgets.QLabel(self.trocador_page)
        self.label_19.setGeometry(QtCore.QRect(290, 180, 47, 13))
        self.label_19.setObjectName("label_19")
        self.window_frame.addWidget(self.trocador_page)
        self.resultados_page = QtWidgets.QWidget()
        self.resultados_page.setObjectName("resultados_page")
        self.label_20 = QtWidgets.QLabel(self.resultados_page)
        self.label_20.setGeometry(QtCore.QRect(280, 240, 47, 13))
        self.label_20.setObjectName("label_20")
        self.window_frame.addWidget(self.resultados_page)
        self.gridLayout_4.addWidget(self.window_frame, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.window_frame.setCurrentIndex(1)
        self.toolBox.setCurrentIndex(1)
        self.toolBox.layout().setSpacing(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.f1T1_entry, self.f1T2_entry)
        MainWindow.setTabOrder(self.f1T2_entry, self.f1Flow_entry)
        MainWindow.setTabOrder(self.f1Flow_entry, self.f1Cp_spinBox)
        MainWindow.setTabOrder(self.f1Cp_spinBox, self.f1Rho_spinBox)
        MainWindow.setTabOrder(self.f1Rho_spinBox, self.f1Mi_spinbox)
        MainWindow.setTabOrder(self.f1Mi_spinbox, self.f1Kf_spinbox)
        MainWindow.setTabOrder(self.f1Kf_spinbox, self.f1R_spinbox)
        MainWindow.setTabOrder(self.f1R_spinbox, self.f2T1_entry)
        MainWindow.setTabOrder(self.f2T1_entry, self.f2T2_entry)
        MainWindow.setTabOrder(self.f2T2_entry, self.f2Flow_entry)
        MainWindow.setTabOrder(self.f2Flow_entry, self.f2Cp_spinBox)
        MainWindow.setTabOrder(self.f2Cp_spinBox, self.f2Rho_spinBox)
        MainWindow.setTabOrder(self.f2Rho_spinBox, self.f2Mi_spinBox)
        MainWindow.setTabOrder(self.f2Mi_spinBox, self.f2K_spinBox)
        MainWindow.setTabOrder(self.f2K_spinBox, self.f2R_spinBox)
        MainWindow.setTabOrder(self.f2R_spinBox, self.f1VerDados_btn)
        MainWindow.setTabOrder(self.f1VerDados_btn, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.radioButton_2)
        MainWindow.setTabOrder(self.radioButton_2, self.radioButton_3)
        MainWindow.setTabOrder(self.radioButton_3, self.radioButton)
        MainWindow.setTabOrder(self.radioButton, self.abrirProjeto_btn)
        MainWindow.setTabOrder(self.abrirProjeto_btn, self.f2VerDados_btn)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "STC - v0.0"))
        self.fluido2_btn.setText(_translate("MainWindow", "Fluido 2"))
        self.fluido2_btn.setShortcut(_translate("MainWindow", "3"))
        self.fluido1_btn.setText(_translate("MainWindow", "Fluido 1"))
        self.fluido1_btn.setShortcut(_translate("MainWindow", "2"))
        self.resultados_btn.setText(_translate("MainWindow", "Resultados"))
        self.resultados_btn.setShortcut(_translate("MainWindow", "5"))
        self.trocador_btn.setText(_translate("MainWindow", "Trocador"))
        self.trocador_btn.setShortcut(_translate("MainWindow", "4"))
        self.projeto_btn.setText(_translate("MainWindow", "Projeto"))
        self.projeto_btn.setShortcut(_translate("MainWindow", "1"))
        self.newFile_btn.setToolTip(_translate("MainWindow", "Novo projeto"))
        self.openFile_btn.setToolTip(_translate("MainWindow", "Abrir projeto"))
        self.saveFile_btn.setToolTip(_translate("MainWindow", "Salvar"))
        self.saveAsFile_btn.setToolTip(_translate("MainWindow", "<html><head/><body><p>Salvar como</p></body></html>"))
        self.calculate_btn.setToolTip(_translate("MainWindow", "Calcular"))
        self.title_label.setText(_translate("MainWindow", "Projeto"))
        self.pushButton_2.setText(_translate("MainWindow", "STC"))
        self.mainTitle_label.setText(_translate("MainWindow", "STC"))
        self.label_17.setText(_translate("MainWindow", "Simulador de trocador de calor"))
        self.radioButton.setText(_translate("MainWindow", "Trocador de placas"))
        self.radioButton_3.setText(_translate("MainWindow", "Bitubular"))
        self.radioButton_2.setText(_translate("MainWindow", "Casco e tubo"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Novo projeto"))
        self.abrirProjeto_btn.setText(_translate("MainWindow", "Abrir projeto"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Carregar projeto"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/logo.jpg\"/>Made with love by <a href=\"https://github.com/Zamariolo/STC\"><span style=\" color:#308f7b;\">STeamC</span></a><a href=\"https://github.com/Zamariolo/STC\"><span style=\" color:#308f7b;\"/></a><img src=\"images/unifei_logo.png\"/></p></body></html>"))
        self.f1Fluids_combobox.setItemText(0, _translate("MainWindow", "Personalizado"))
        self.f1Fluids_combobox.setItemText(1, _translate("MainWindow", "Água"))
        self.f1Fluids_combobox.setItemText(2, _translate("MainWindow", "Amonia"))
        self.f1Fluids_combobox.setItemText(3, _translate("MainWindow", "Benzeno"))
        self.f1Fluids_combobox.setItemText(4, _translate("MainWindow", "Tolueno"))
        self.f1Fluids_label.setText(_translate("MainWindow", "Selecionar fluido"))
        self.f1T1Unit_comboBox.setItemText(0, _translate("MainWindow", "ºC"))
        self.f1T1Unit_comboBox.setItemText(1, _translate("MainWindow", "K"))
        self.f1T1Unit_comboBox.setItemText(2, _translate("MainWindow", "ºF"))
        self.f1T1Unit_comboBox.setItemText(3, _translate("MainWindow", "R"))
        self.f1Flow_label.setText(_translate("MainWindow", "Vazão do fluido"))
        self.f1T1_label.setText(_translate("MainWindow", "Temperatura de entrada do fluido"))
        self.f1R_label.setText(_translate("MainWindow", "Fator de incrustação (R)"))
        self.f1Cp_label.setText(_translate("MainWindow", "Calor específico (Cp)"))
        self.f1Mi_label.setText(_translate("MainWindow", "Viscosidade dinâmica (μ)"))
        self.f1Image_label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/Plate_heat_exchanger.jpg\"/></p></body></html>"))
        self.f1RUnit_label.setText(_translate("MainWindow", "[(s.m².K)/J]"))
        self.f1CpUnit_label.setText(_translate("MainWindow", "[kJ/(kg.K)]"))
        self.f1MiUnit_label.setText(_translate("MainWindow", "[μPa.s]"))
        self.f1Rho_label.setText(_translate("MainWindow", "<html><head/><body><p>Massa específica (ρ)</p></body></html>"))
        self.f1RhoUnit_label.setText(_translate("MainWindow", "[kg/m³]"))
        self.f1KUnit_label.setText(_translate("MainWindow", "[mW/(m.K)]"))
        self.f1K_label.setText(_translate("MainWindow", "Condutividade térmica (k)"))
        self.f1FlowUnit_comboBox.setItemText(0, _translate("MainWindow", "kg/h"))
        self.f1FlowUnit_comboBox.setItemText(1, _translate("MainWindow", "g/s"))
        self.f1FlowUnit_comboBox.setItemText(2, _translate("MainWindow", "L/s"))
        self.f1FlowUnit_comboBox.setItemText(3, _translate("MainWindow", "m³/h"))
        self.f1T2_label.setText(_translate("MainWindow", "Temperatura de saída do fluido"))
        self.f1VerDados_btn.setText(_translate("MainWindow", "Ver dados"))
        self.f1TUnit_label.setText(_translate("MainWindow", "ºC"))
        self.f1Warning_label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/warning.png\"/></p></body></html>"))
        self.f1Tm_label.setText(_translate("MainWindow", "Fluido avaliado em 4000ºC"))
        self.f2RUnit_label.setText(_translate("MainWindow", "[(s.m².K)/J]"))
        self.f2T2_label.setText(_translate("MainWindow", "Temperatura de saída do fluido"))
        self.f2KUnit_label.setText(_translate("MainWindow", "[mW/(m.K)]"))
        self.f2T1_label.setText(_translate("MainWindow", "Temperatura de entrada do fluido"))
        self.f2RhoUnit_label.setText(_translate("MainWindow", "[kg/m³]"))
        self.f2Mi_label.setText(_translate("MainWindow", "Viscosidade dinâmica (μ)"))
        self.f2MiUnit_label.setText(_translate("MainWindow", "[μPa.s]"))
        self.f2R_label.setText(_translate("MainWindow", "Fator de incrustação (R)"))
        self.f2K_label.setText(_translate("MainWindow", "Condutividade térmica (k)"))
        self.f2Image_label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/Plate_heat_exchanger.jpg\"/></p></body></html>"))
        self.f2Flow_label.setText(_translate("MainWindow", "Vazão do fluido"))
        self.f2T1Unit_comboBox.setItemText(0, _translate("MainWindow", "ºC"))
        self.f2T1Unit_comboBox.setItemText(1, _translate("MainWindow", "K"))
        self.f2T1Unit_comboBox.setItemText(2, _translate("MainWindow", "ºF"))
        self.f2T1Unit_comboBox.setItemText(3, _translate("MainWindow", "R"))
        self.f2FlowUnit_comboBox.setItemText(0, _translate("MainWindow", "kg/h"))
        self.f2FlowUnit_comboBox.setItemText(1, _translate("MainWindow", "g/s"))
        self.f2FlowUnit_comboBox.setItemText(2, _translate("MainWindow", "L/s"))
        self.f2FlowUnit_comboBox.setItemText(3, _translate("MainWindow", "m³/h"))
        self.f2Cp_label.setText(_translate("MainWindow", "Calor específico (Cp)"))
        self.f2CpUnit_label.setText(_translate("MainWindow", "[kJ/(kg.K)]"))
        self.f2Fluids_label.setText(_translate("MainWindow", "Selecionar fluido"))
        self.f2Rho_label.setText(_translate("MainWindow", "<html><head/><body><p>Massa específica (ρ)</p></body></html>"))
        self.f2Warning_label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/warning.png\"/></p></body></html>"))
        self.f2Tm_label.setText(_translate("MainWindow", "Fluido avaliado em 4000ºC"))
        self.f2Fluids_comboBox.setItemText(0, _translate("MainWindow", "Personalizado"))
        self.f2Fluids_comboBox.setItemText(1, _translate("MainWindow", "Água"))
        self.f2Fluids_comboBox.setItemText(2, _translate("MainWindow", "Amonia"))
        self.f2Fluids_comboBox.setItemText(3, _translate("MainWindow", "Benzeno"))
        self.f2Fluids_comboBox.setItemText(4, _translate("MainWindow", "Tolueno"))
        self.f2VerDados_btn.setText(_translate("MainWindow", "Ver dados"))
        self.f2TUnit_label.setText(_translate("MainWindow", "ºC"))
        self.label_19.setText(_translate("MainWindow", "Trocador"))
        self.label_20.setText(_translate("MainWindow", "Resultados"))

###############################################################################
        #   Codigos de autoria humana
        #   Adicionando funcionalidade aos botoes
###############################################################################
    
        #Carregamento inicial e gatilhos pras funções

        if 1:     #Carregando fluidos pro sistema
            fluidos = Nome_fluidos()
            fluidos.insert(0, "Personalizado")
            list_fluidos = []
            for i in fluidos:
                i = i.title()
                list_fluidos.append(i)
            #Atualiza lista de fluidos da tela do fluido 1 e 2
            self.f1Fluids_combobox.clear()
            self.f2Fluids_comboBox.clear()
            self.f1Fluids_combobox.addItems(list_fluidos)
            self.f2Fluids_comboBox.addItems(list_fluidos)

            #Widgets que terao valores salvos no arquivo .stc
            spinBoxSalvos = ['f1T1_entry', 'f1T2_entry', 'f2T1_entry', 'f2T2_entry', 'f1Cp_spinBox', 'f1Rho_spinBox', 'f1Mi_spinbox', 'f1Kf_spinbox', 'f1R_spinbox', 'f2Cp_spinBox', 'f2Rho_spinBox', 'f2Mi_spinBox', 'f2K_spinBox', 'f2R_spinBox', 'f1Flow_entry', 'f2Flow_entry']
            comboBoxSalvos = ['f1T1Unit_comboBox','f2T1Unit_comboBox', 'f1FlowUnit_comboBox', 'f1Fluids_combobox', 'f2FlowUnit_comboBox', 'f2Fluids_comboBox']
            #Nome do projeto
            self.nomeProjeto = "UmNomeQueNinguemNuncaVaiEscolher"

            #Aspectos graficos iniciais
            self.f1Warning_label.hide()
            self.f2Warning_label.hide()
            self.f1Tm_label.setText("")
            self.f2Tm_label.setText("")

            #######################################################################
            ############### GATILHOS PRAS FUNÇÕES #################################
            #######################################################################

            #self.btn_origem.clicked.connect(self.correioEnderecoOrigem)   -- SEM PARAMETROS
            #Ligacao pros botoes
            self.projeto_btn.clicked.connect(partial(self.trocaTela, tela=str("projetoTela")))
            self.fluido1_btn.clicked.connect(partial(self.trocaTela, tela=str("fluido1Tela")))
            self.fluido2_btn.clicked.connect(partial(self.trocaTela, tela=str("fluido2Tela")))
            self.trocador_btn.clicked.connect(partial(self.trocaTela, tela=str("trocadorTela")))
            self.resultados_btn.clicked.connect(partial(self.trocaTela, tela=str("resultadosTela")))

            #Combobox de fluidos
            self.f1Fluids_combobox.currentIndexChanged.connect(partial(self.atualizaDadosFluido, fluido=1))
            self.f2Fluids_comboBox.currentIndexChanged.connect(partial(self.atualizaDadosFluido, fluido=2))
            self.f1T1_entry.valueChanged.connect(partial(self.atualizaDadosFluido, fluido=1))
            self.f1T2_entry.valueChanged.connect(partial(self.atualizaDadosFluido, fluido=1))
            self.f2T1_entry.valueChanged.connect(partial(self.atualizaDadosFluido, fluido=2))
            self.f2T2_entry.valueChanged.connect(partial(self.atualizaDadosFluido, fluido=2))

            #Combobox de unidades de temperatura
            self.f1T1Unit_comboBox.currentIndexChanged.connect(partial(self.atualizaDadosFluido, fluido=1))
            self.f2T1Unit_comboBox.currentIndexChanged.connect(partial(self.atualizaDadosFluido, fluido=2))

            #Botoes de novo, abrir, salvar, calcular
            self.abrirProjeto_btn.clicked.connect(partial(self.abrirProjeto))
            self.saveFile_btn.clicked.connect(partial(self.salvarProjeto, spinBox=spinBoxSalvos, comboBox=comboBoxSalvos, funcao="salvar"))
            self.saveAsFile_btn.clicked.connect(partial(self.salvarProjeto, spinBox=spinBoxSalvos, comboBox=comboBoxSalvos, funcao="salvarComo"))
            self.openFile_btn.clicked.connect(partial(self.abrirProjeto))
            self.newFile_btn.clicked.connect(partial(self.novoProjeto, spinBoxSalvos=spinBoxSalvos, comboBoxSalvos=comboBoxSalvos))
    
    ###################################################################################
    ### FUNÇÕES QUE INTERMEDIAM TELA GRAFICA vs ROTINAS DE CALCULO E BANCO DE DADOS ###
    ###################################################################################

    def trocaTela(self, tela):
        '''Descr: Funcao que muda a tela ativa do programa
        '''
        #Para efeitos visuais | Reseta todos os botoes sem negrito
        #Posteriormente, somente o botao selecionado ira ficar negrito
        nomeBtns = ['projeto_btn', 'fluido1_btn', 'fluido2_btn', 'trocador_btn', 'resultados_btn']
        for nomeWidget in nomeBtns:
            widget = self.centralwidget.findChild(QtCore.QObject, nomeWidget)
            widget.setStyleSheet('background-color:rgb(217, 217, 217); color: rgb(48, 143, 123);')
            widget.setEnabled(True)
            

        if tela=='projetoTela':
            self.window_frame.setCurrentIndex(0)
            self.title_label.setText("Projeto")
            self.projeto_btn.setStyleSheet('background-color:rgb(217, 217, 217); color: rgb(0, 227, 178)')
            self.projeto_btn.setEnabled(False)      
        elif tela=="fluido1Tela":
            self.window_frame.setCurrentIndex(1)
            self.title_label.setText("Fluido 1")
            self.fluido1_btn.setStyleSheet('background-color:rgb(217, 217, 217); color: rgb(0, 227, 178)')
            self.fluido1_btn.setEnabled(False)
        elif tela=="fluido2Tela":
            self.window_frame.setCurrentIndex(2)
            self.title_label.setText("Fluido 2")
            self.fluido2_btn.setStyleSheet('background-color:rgb(217, 217, 217); color: rgb(0, 227, 178)')
            self.fluido2_btn.setEnabled(False)
        elif tela=="trocadorTela":
            self.window_frame.setCurrentIndex(3)
            self.title_label.setText("Trocador")
            self.trocador_btn.setStyleSheet('background-color:rgb(217, 217, 217); color: rgb(0, 227, 178)')
            self.trocador_btn.setEnabled(False)
        elif tela=="resultadosTela":
            self.window_frame.setCurrentIndex(4)
            self.title_label.setText("Resultados")
            self.resultados_btn.setStyleSheet('background-color:rgb(217, 217, 217); color: rgb(0, 227, 178)')
            self.resultados_btn.setEnabled(False)

    def atualizaDadosFluido(self, fluido):
        '''Descr: Carrega a propriedade do fluido selecionado apresentando os valores na tela grafica
        '''
        #Carrega propriedades do fluido 1
        if fluido == 1:
            fluid = self.f1Fluids_combobox.currentText()

            T1 = float(self.f1T1_entry.value())
            T2 = float(self.f1T2_entry.value())
            Tunidade = self.f1T1Unit_comboBox.currentText()     #Adquire temperaturas e unidade
            self.f1TUnit_label.setText(Tunidade)                #Atualiza unidades
            tm = (T1+T2)/2.0

            if fluid != "Personalizado":
                T1 = ConverterTemperatura(Tunidade, T1)
                T2 = ConverterTemperatura(Tunidade, T2) #Converte temperaturas
                [rho,cp,kf,mi,pr, aviso] = tabela_fluidos(fluid, T1, T2)
                self.f1Cp_spinBox.setValue(cp)
                self.f1Rho_spinBox.setValue(rho)
                self.f1Mi_spinbox.setValue(mi)
                self.f1Kf_spinbox.setValue(kf)
                self.f1R_spinbox.setValue(0)

                #Apresentando valor medio de temperatura
                self.f1Tm_label.setText("Fluido avaliado em %.2f %s" %(tm, Tunidade))

                if aviso==0:
                    self.f1Warning_label.hide()
                elif aviso==1:
                    self.f1Warning_label.show()
                    self.f1Warning_label.setToolTip('[Dados extrapolados] Temperatura avaliada abaixo do intervalo do banco de dados')
                elif aviso==2:
                    self.f1Warning_label.show()
                    self.f1Warning_label.setToolTip('[Dados extrapolados] Temperatura avaliada acima do intervalo do banco de dados')
            
            elif fluid=="Personalizado":
                self.f1Warning_label.hide()
                self.f1Tm_label.setText("Fluido avaliado em %.2f %s" %(tm, Tunidade))

        #Carrega as propriedades do fluido 2
        elif fluido == 2:
            fluid = self.f2Fluids_comboBox.currentText()
            T1 = float(self.f2T1_entry.value())
            T2 = float(self.f2T2_entry.value())
            Tunidade = self.f2T1Unit_comboBox.currentText()     #Adquire temperaturas e unidade
            self.f2TUnit_label.setText(Tunidade)                #Atualiza unidades
            tm = (T1+T2)/2.0
            
            if fluid != "Personalizado":
                T1 = ConverterTemperatura(Tunidade, T1)
                T2 = ConverterTemperatura(Tunidade, T2) #Converte temperaturas  
                [rho,cp,kf,mi,pr, aviso] = tabela_fluidos(fluid, T1, T2)
                self.f2Cp_spinBox.setValue(cp)
                self.f2Rho_spinBox.setValue(rho)
                self.f2Mi_spinBox.setValue(mi)
                self.f2K_spinBox.setValue(kf)
                self.f2R_spinBox.setValue(0)

                #Apresentando valor medio de temperatura
                self.f2Tm_label.setText("Fluido avaliado em %.2f %s" %(tm, Tunidade))

                if aviso==0:
                    self.f2Warning_label.hide()
                elif aviso==1:
                    self.f2Warning_label.show()
                    self.f2Warning_label.setToolTip('[Dados extrapolados] Temperatura avaliada abaixo do intervalo do banco de dados')
                elif aviso==2:
                    self.f2Warning_label.show()
                    self.f2Warning_label.setToolTip('[Dados extrapolados] Temperatura avaliada acima do intervalo do banco de dados')
            
            elif fluid=="Personalizado":
                self.f2Warning_label.hide()
                self.f2Tm_label.setText("Fluido avaliado em %.2f %s" %(tm, Tunidade))

    def atualizaTituloPrograma(self, nomeArquivo):
            #Obter somente o nome do projeto e nao do diretorio

            #print(nomeArquivo)
            index = 0
            finalIndex = len(nomeArquivo)  #Antianta
            for letra in nomeArquivo:
                index = index + 1
                if letra=='/':
                    finalIndex = index
            #Atualizar titulo do programa
            nomeProjeto = nomeArquivo[finalIndex:len(self.nomeProjeto)-4]
            MainWindow.setWindowTitle("STC - v0.0 - %s" %nomeProjeto)

    def salvarProjeto(self, spinBox, comboBox, funcao):

        if funcao=="salvar":
            if self.nomeProjeto == "UmNomeQueNinguemNuncaVaiEscolher":
                funcao = "salvarComo"
                self.salvarProjeto(spinBox, comboBox, funcao)
                return 0
            else:
                nomeArquivo = self.nomeProjeto

        elif funcao=="salvarComo":
            nomeArquivo = QtWidgets.QFileDialog.getSaveFileName(self.centralwidget, 'Salvar Arquivo', filter='*.stc')
            nomeArquivo = str(nomeArquivo[0])

            #Operacao cancelada (Anti anta)
            if nomeArquivo=="": 
                return 0

        saveText = ""
        #Salva dados dos comboBox'es
        for nomeWidget in comboBox:
            widget = self.centralwidget.findChild(QtCore.QObject, nomeWidget)
            saveText = saveText + nomeWidget + ","+ str(widget.currentIndex()) + "," + str(widget.currentText()) + "\n"

        saveText = saveText + "[spinBox]\n"

        #Salva dados dos spinBox'es
        for nomeWidget in spinBox:
            #print(nomeWidget)
            widget = self.centralwidget.findChild(QtCore.QObject, nomeWidget)
            saveText = saveText + nomeWidget + "," + str(widget.value()) + "\n"

        #Salvando em arquivo .stc
        saveFile = open(r"%s" %nomeArquivo, "w")
        saveFile.write(saveText)
        saveFile.close()

        self.nomeProjeto = nomeArquivo
        
        '''
        #Obter somente o nome do projeto e nao do diretorio
        index = 0
        for letra in nomeArquivo:
            index = index + 1
            if letra=='/':
                finalIndex = index
        #Atualizar titulo do programa'''
        self.atualizaTituloPrograma(self.nomeProjeto)

    def abrirProjeto(self):
        #Carregar arquivo
        nomeArquivo = QtWidgets.QFileDialog.getOpenFileName(self.centralwidget, 'Abrir projeto', filter="*.stc")
        nomeArquivo = str(nomeArquivo[0])

        #Operacao cancelada (anti anta)
        if nomeArquivo=="":
            return 0

        self.nomeProjeto = nomeArquivo
        self.atualizaTituloPrograma(self.nomeProjeto)
        self.trocaTela('fluido1Tela')

        #Percorre linha por linha do arquivo
        with open(r"%s" %nomeArquivo) as file:
            cont = 0
            tipo = 'comboBox'
            for line in file:
                #Determinando o tipo de objeto
                if line == "[spinBox]\n":
                    tipo = 'spinBox'
                    continue
                #Percorrendo a linha
                index = 0
                for letra in line:
                    if letra=="," and line!="[spinBox]":
                        finalIndex = index
                        break
                    else:
                        index = index + 1
                    
                nomeWidget = line[0:finalIndex]
                widget = self.centralwidget.findChild(QtCore.QObject, nomeWidget)
                
                #Verificando o tipo
                if tipo=="spinBox":
                    valor = float(line[finalIndex+1:len(line)-2])
                    widget.setValue(valor)

                elif tipo=="comboBox":
                    valor = int(line[finalIndex+1])
                    widget.setCurrentIndex(valor)
                    antigoText = line[finalIndex+3:len(line)-1]
                    if antigoText!=widget.currentText():
                        print("Aparentemente um erro ocorreu ao encontrar o fluido")
                        widget.setCurrentIndex(0)

    def novoProjeto(self, comboBoxSalvos, spinBoxSalvos):
        self.atualizaTituloPrograma("/*")
        self.nomeProjeto = "UmNomeQueNinguemNuncaVaiEscolher"
        self.trocaTela('fluido1Tela')

        for nomeWidget in comboBoxSalvos:
            widget = self.centralwidget.findChild(QtCore.QObject, nomeWidget)
            widget.setCurrentIndex(0)
        for nomeWidget in spinBoxSalvos:
            widget = self.centralwidget.findChild(QtCore.QObject, nomeWidget)
            widget.setValue(0.0)


#import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

