# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Tela.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from libSTC import Nome_fluidos, tabela_fluidos
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.ApplicationModal)
        MainWindow.resize(771, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet("background-color: rgb(237, 237, 237);")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setContentsMargins(2, 1, 1, 1)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setContentsMargins(0, -1, -1, -1)
        self.gridLayout_4.setSpacing(1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.timeEdit = QtWidgets.QTimeEdit(self.centralwidget)
        self.timeEdit.setStyleSheet("")
        self.timeEdit.setFrame(False)
        self.timeEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.timeEdit.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setTimeSpec(QtCore.Qt.TimeZone)
        self.timeEdit.setObjectName("timeEdit")
        self.gridLayout_4.addWidget(self.timeEdit, 0, 0, 1, 1)
        self.window_frame = QtWidgets.QStackedWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.window_frame.sizePolicy().hasHeightForWidth())
        self.window_frame.setSizePolicy(sizePolicy)
        self.window_frame.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.window_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.window_frame.setLineWidth(5)
        self.window_frame.setObjectName("window_frame")
        self.projeto_page = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projeto_page.sizePolicy().hasHeightForWidth())
        self.projeto_page.setSizePolicy(sizePolicy)
        self.projeto_page.setObjectName("projeto_page")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.projeto_page)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.titulo_frame = QtWidgets.QFrame(self.projeto_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titulo_frame.sizePolicy().hasHeightForWidth())
        self.titulo_frame.setSizePolicy(sizePolicy)
        self.titulo_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titulo_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo_frame.setObjectName("titulo_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.titulo_frame)
        self.verticalLayout.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainTitle_label = QtWidgets.QLabel(self.titulo_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainTitle_label.sizePolicy().hasHeightForWidth())
        self.mainTitle_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(40)
        self.mainTitle_label.setFont(font)
        self.mainTitle_label.setAlignment(QtCore.Qt.AlignCenter)
        self.mainTitle_label.setObjectName("mainTitle_label")
        self.verticalLayout.addWidget(self.mainTitle_label)
        self.label_17 = QtWidgets.QLabel(self.titulo_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.verticalLayout.addWidget(self.label_17)
        self.verticalLayout_5.addWidget(self.titulo_frame)
        self.projeto_frame = QtWidgets.QFrame(self.projeto_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.projeto_frame.sizePolicy().hasHeightForWidth())
        self.projeto_frame.setSizePolicy(sizePolicy)
        self.projeto_frame.setStyleSheet("")
        self.projeto_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.projeto_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.projeto_frame.setObjectName("projeto_frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.projeto_frame)
        self.horizontalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.toolBox = QtWidgets.QToolBox(self.projeto_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBox.sizePolicy().hasHeightForWidth())
        self.toolBox.setSizePolicy(sizePolicy)
        self.toolBox.setMinimumSize(QtCore.QSize(166, 0))
        self.toolBox.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.toolBox.setFrameShape(QtWidgets.QFrame.Box)
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 164, 81))
        self.page.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.page.setObjectName("page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.radioButton = QtWidgets.QRadioButton(self.page)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_4.addWidget(self.radioButton)
        self.radioButton_3 = QtWidgets.QRadioButton(self.page)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_4.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.page)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_4.addWidget(self.radioButton_2)
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 164, 69))
        self.page_2.setObjectName("page_2")
        self.toolBox.addItem(self.page_2, "")
        self.horizontalLayout_2.addWidget(self.toolBox)
        self.verticalLayout_5.addWidget(self.projeto_frame)
        self.label_34 = QtWidgets.QLabel(self.projeto_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_34.sizePolicy().hasHeightForWidth())
        self.label_34.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setAlignment(QtCore.Qt.AlignCenter)
        self.label_34.setObjectName("label_34")
        self.verticalLayout_5.addWidget(self.label_34)
        self.window_frame.addWidget(self.projeto_page)
        self.fluido1_page = QtWidgets.QWidget()
        self.fluido1_page.setObjectName("fluido1_page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.fluido1_page)
        self.gridLayout_2.setContentsMargins(40, 9, -1, -1)
        self.gridLayout_2.setHorizontalSpacing(10)
        self.gridLayout_2.setVerticalSpacing(5)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_11 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_2.addWidget(self.label_11, 21, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 17, 3, 1, 1)
        self.fluidos_combobox = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fluidos_combobox.sizePolicy().hasHeightForWidth())
        self.fluidos_combobox.setSizePolicy(sizePolicy)
        self.fluidos_combobox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.fluidos_combobox.setFont(font)
        self.fluidos_combobox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fluidos_combobox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fluidos_combobox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fluidos_combobox.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.fluidos_combobox.setFrame(False)
        self.fluidos_combobox.setModelColumn(0)
        self.fluidos_combobox.setObjectName("fluidos_combobox")
        self.fluidos_combobox.addItem("")
        self.fluidos_combobox.addItem("")
        self.fluidos_combobox.addItem("")
        self.fluidos_combobox.addItem("")
        self.fluidos_combobox.addItem("")
        self.gridLayout_2.addWidget(self.fluidos_combobox, 19, 0, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 18, 0, 1, 2)
        self.comboBox = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox.setFrame(False)
        self.comboBox.setModelColumn(0)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 2, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_3.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_3.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_3.setFrame(False)
        self.comboBox_3.setModelColumn(0)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_3, 6, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 3, 0, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 5, 0, 1, 1)
        self.T1_entry = QtWidgets.QSpinBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T1_entry.sizePolicy().hasHeightForWidth())
        self.T1_entry.setSizePolicy(sizePolicy)
        self.T1_entry.setMinimumSize(QtCore.QSize(0, 24))
        self.T1_entry.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.T1_entry.setFont(font)
        self.T1_entry.setMouseTracking(False)
        self.T1_entry.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.T1_entry.setAcceptDrops(False)
        self.T1_entry.setToolTip("")
        self.T1_entry.setToolTipDuration(-1)
        self.T1_entry.setStatusTip("")
        self.T1_entry.setWhatsThis("")
        self.T1_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T1_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.T1_entry.setWrapping(False)
        self.T1_entry.setFrame(False)
        self.T1_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.T1_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.T1_entry.setAccelerated(True)
        self.T1_entry.setKeyboardTracking(True)
        self.T1_entry.setProperty("showGroupSeparator", False)
        self.T1_entry.setMinimum(-9999)
        self.T1_entry.setMaximum(9999)
        self.T1_entry.setSingleStep(2)
        self.T1_entry.setDisplayIntegerBase(10)
        self.T1_entry.setObjectName("T1_entry")
        self.gridLayout_2.addWidget(self.T1_entry, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 1, 0, 1, 2)
        self.vazao_entry = QtWidgets.QSpinBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vazao_entry.sizePolicy().hasHeightForWidth())
        self.vazao_entry.setSizePolicy(sizePolicy)
        self.vazao_entry.setMinimumSize(QtCore.QSize(0, 24))
        self.vazao_entry.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.vazao_entry.setFont(font)
        self.vazao_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vazao_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.vazao_entry.setWrapping(False)
        self.vazao_entry.setFrame(False)
        self.vazao_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.vazao_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vazao_entry.setAccelerated(True)
        self.vazao_entry.setKeyboardTracking(True)
        self.vazao_entry.setProperty("showGroupSeparator", False)
        self.vazao_entry.setMinimum(-9999)
        self.vazao_entry.setMaximum(9999)
        self.vazao_entry.setDisplayIntegerBase(10)
        self.vazao_entry.setObjectName("vazao_entry")
        self.gridLayout_2.addWidget(self.vazao_entry, 6, 0, 1, 1)
        self.T2_entry = QtWidgets.QSpinBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T2_entry.sizePolicy().hasHeightForWidth())
        self.T2_entry.setSizePolicy(sizePolicy)
        self.T2_entry.setMinimumSize(QtCore.QSize(0, 24))
        self.T2_entry.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.T2_entry.setFont(font)
        self.T2_entry.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T2_entry.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.T2_entry.setWrapping(False)
        self.T2_entry.setFrame(False)
        self.T2_entry.setAlignment(QtCore.Qt.AlignCenter)
        self.T2_entry.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.T2_entry.setAccelerated(True)
        self.T2_entry.setKeyboardTracking(True)
        self.T2_entry.setProperty("showGroupSeparator", False)
        self.T2_entry.setMinimum(-9999)
        self.T2_entry.setMaximum(9999)
        self.T2_entry.setDisplayIntegerBase(10)
        self.T2_entry.setObjectName("T2_entry")
        self.gridLayout_2.addWidget(self.T2_entry, 4, 0, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_2.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_2.setFrame(False)
        self.comboBox_2.setModelColumn(0)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_2, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 19, 3, 1, 1)
        self.line_6 = QtWidgets.QFrame(self.fluido1_page)
        self.line_6.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.gridLayout_2.addWidget(self.line_6, 17, 2, 5, 1)
        self.label = QtWidgets.QLabel(self.fluido1_page)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 1, 3, 5, 3)
        self.label_14 = QtWidgets.QLabel(self.fluido1_page)
        self.label_14.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.gridLayout_2.addWidget(self.label_14, 19, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.fluido1_page)
        self.label_16.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_2.addWidget(self.label_16, 21, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.fluido1_page)
        self.label_13.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayout_2.addWidget(self.label_13, 18, 5, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.fluido1_page)
        self.label_12.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.gridLayout_2.addWidget(self.label_12, 17, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 18, 3, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.fluido1_page)
        self.line_5.setStyleSheet("")
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setLineWidth(1)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setObjectName("line_5")
        self.gridLayout_2.addWidget(self.line_5, 14, 0, 1, 6)
        self.label_15 = QtWidgets.QLabel(self.fluido1_page)
        self.label_15.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_2.addWidget(self.label_15, 20, 5, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.fluido1_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_2.addWidget(self.label_10, 20, 3, 1, 1)
        self.cp_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.cp_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cp_spinbox.setFont(font)
        self.cp_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.cp_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.cp_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cp_spinbox.setMinimum(-99999.0)
        self.cp_spinbox.setMaximum(999999.0)
        self.cp_spinbox.setObjectName("cp_spinbox")
        self.gridLayout_2.addWidget(self.cp_spinbox, 17, 4, 1, 1)
        self.rho_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.rho_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.rho_spinbox.setFont(font)
        self.rho_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.rho_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.rho_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rho_spinbox.setMinimum(-99999.0)
        self.rho_spinbox.setMaximum(999999.0)
        self.rho_spinbox.setObjectName("rho_spinbox")
        self.gridLayout_2.addWidget(self.rho_spinbox, 18, 4, 1, 1)
        self.mi_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.mi_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.mi_spinbox.setFont(font)
        self.mi_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.mi_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.mi_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.mi_spinbox.setMinimum(-99999.0)
        self.mi_spinbox.setMaximum(999999.0)
        self.mi_spinbox.setObjectName("mi_spinbox")
        self.gridLayout_2.addWidget(self.mi_spinbox, 19, 4, 1, 1)
        self.kf_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.kf_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.kf_spinbox.setFont(font)
        self.kf_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.kf_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.kf_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kf_spinbox.setMinimum(-99999.0)
        self.kf_spinbox.setMaximum(999999.0)
        self.kf_spinbox.setObjectName("kf_spinbox")
        self.gridLayout_2.addWidget(self.kf_spinbox, 20, 4, 1, 1)
        self.r_spinbox = QtWidgets.QDoubleSpinBox(self.fluido1_page)
        self.r_spinbox.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.r_spinbox.setFont(font)
        self.r_spinbox.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.r_spinbox.setAlignment(QtCore.Qt.AlignCenter)
        self.r_spinbox.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.r_spinbox.setMinimum(-99999.0)
        self.r_spinbox.setMaximum(999999.0)
        self.r_spinbox.setObjectName("r_spinbox")
        self.gridLayout_2.addWidget(self.r_spinbox, 21, 4, 1, 1)
        self.window_frame.addWidget(self.fluido1_page)
        self.fluido2_page = QtWidgets.QWidget()
        self.fluido2_page.setObjectName("fluido2_page")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.fluido2_page)
        self.gridLayout_5.setContentsMargins(40, -1, -1, -1)
        self.gridLayout_5.setHorizontalSpacing(10)
        self.gridLayout_5.setVerticalSpacing(5)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_3 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_5.addWidget(self.label_3, 0, 0, 1, 2)
        self.label_30 = QtWidgets.QLabel(self.fluido2_page)
        self.label_30.setAlignment(QtCore.Qt.AlignCenter)
        self.label_30.setObjectName("label_30")
        self.gridLayout_5.addWidget(self.label_30, 0, 3, 5, 3)
        self.T1_entry_2 = QtWidgets.QSpinBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T1_entry_2.sizePolicy().hasHeightForWidth())
        self.T1_entry_2.setSizePolicy(sizePolicy)
        self.T1_entry_2.setMinimumSize(QtCore.QSize(0, 24))
        self.T1_entry_2.setMaximumSize(QtCore.QSize(200, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.T1_entry_2.setFont(font)
        self.T1_entry_2.setMouseTracking(False)
        self.T1_entry_2.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.T1_entry_2.setAcceptDrops(False)
        self.T1_entry_2.setToolTip("")
        self.T1_entry_2.setToolTipDuration(-1)
        self.T1_entry_2.setStatusTip("")
        self.T1_entry_2.setWhatsThis("")
        self.T1_entry_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T1_entry_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.T1_entry_2.setWrapping(False)
        self.T1_entry_2.setFrame(False)
        self.T1_entry_2.setAlignment(QtCore.Qt.AlignCenter)
        self.T1_entry_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.T1_entry_2.setAccelerated(True)
        self.T1_entry_2.setKeyboardTracking(True)
        self.T1_entry_2.setProperty("showGroupSeparator", False)
        self.T1_entry_2.setMinimum(-9999)
        self.T1_entry_2.setMaximum(9999)
        self.T1_entry_2.setSingleStep(2)
        self.T1_entry_2.setDisplayIntegerBase(10)
        self.T1_entry_2.setObjectName("T1_entry_2")
        self.gridLayout_5.addWidget(self.T1_entry_2, 1, 0, 1, 1)
        self.comboBox_5 = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_5.sizePolicy().hasHeightForWidth())
        self.comboBox_5.setSizePolicy(sizePolicy)
        self.comboBox_5.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_5.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_5.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_5.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_5.setFrame(False)
        self.comboBox_5.setModelColumn(0)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_5, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        self.label_18.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 2, 0, 1, 2)
        self.T2_entry_2 = QtWidgets.QSpinBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.T2_entry_2.sizePolicy().hasHeightForWidth())
        self.T2_entry_2.setSizePolicy(sizePolicy)
        self.T2_entry_2.setMinimumSize(QtCore.QSize(0, 24))
        self.T2_entry_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.T2_entry_2.setFont(font)
        self.T2_entry_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.T2_entry_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.T2_entry_2.setWrapping(False)
        self.T2_entry_2.setFrame(False)
        self.T2_entry_2.setAlignment(QtCore.Qt.AlignCenter)
        self.T2_entry_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.T2_entry_2.setAccelerated(True)
        self.T2_entry_2.setKeyboardTracking(True)
        self.T2_entry_2.setProperty("showGroupSeparator", False)
        self.T2_entry_2.setMinimum(-9999)
        self.T2_entry_2.setMaximum(9999)
        self.T2_entry_2.setDisplayIntegerBase(10)
        self.T2_entry_2.setObjectName("T2_entry_2")
        self.gridLayout_5.addWidget(self.T2_entry_2, 3, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_4.sizePolicy().hasHeightForWidth())
        self.comboBox_4.setSizePolicy(sizePolicy)
        self.comboBox_4.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_4.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_4.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_4.setFrame(False)
        self.comboBox_4.setModelColumn(0)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_4, 3, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_27.sizePolicy().hasHeightForWidth())
        self.label_27.setSizePolicy(sizePolicy)
        self.label_27.setMaximumSize(QtCore.QSize(400, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.gridLayout_5.addWidget(self.label_27, 4, 0, 1, 1)
        self.vazao_entry_2 = QtWidgets.QSpinBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vazao_entry_2.sizePolicy().hasHeightForWidth())
        self.vazao_entry_2.setSizePolicy(sizePolicy)
        self.vazao_entry_2.setMinimumSize(QtCore.QSize(0, 24))
        self.vazao_entry_2.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.vazao_entry_2.setFont(font)
        self.vazao_entry_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vazao_entry_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.vazao_entry_2.setWrapping(False)
        self.vazao_entry_2.setFrame(False)
        self.vazao_entry_2.setAlignment(QtCore.Qt.AlignCenter)
        self.vazao_entry_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.vazao_entry_2.setAccelerated(True)
        self.vazao_entry_2.setKeyboardTracking(True)
        self.vazao_entry_2.setProperty("showGroupSeparator", False)
        self.vazao_entry_2.setMinimum(-9999)
        self.vazao_entry_2.setMaximum(9999)
        self.vazao_entry_2.setDisplayIntegerBase(10)
        self.vazao_entry_2.setObjectName("vazao_entry_2")
        self.gridLayout_5.addWidget(self.vazao_entry_2, 5, 0, 1, 1)
        self.comboBox_6 = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_6.sizePolicy().hasHeightForWidth())
        self.comboBox_6.setSizePolicy(sizePolicy)
        self.comboBox_6.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBox_6.setMaximumSize(QtCore.QSize(70, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.comboBox_6.setFont(font)
        self.comboBox_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.comboBox_6.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.comboBox_6.setFrame(False)
        self.comboBox_6.setModelColumn(0)
        self.comboBox_6.setObjectName("comboBox_6")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_6, 5, 1, 1, 1)
        self.line_8 = QtWidgets.QFrame(self.fluido2_page)
        self.line_8.setStyleSheet("")
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setLineWidth(1)
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setObjectName("line_8")
        self.gridLayout_5.addWidget(self.line_8, 6, 0, 1, 6)
        self.line_7 = QtWidgets.QFrame(self.fluido2_page)
        self.line_7.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.gridLayout_5.addWidget(self.line_7, 7, 2, 5, 1)
        self.label_25 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_25.sizePolicy().hasHeightForWidth())
        self.label_25.setSizePolicy(sizePolicy)
        self.label_25.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 7, 3, 1, 1)
        self.cp_spinbox_2 = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.cp_spinbox_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.cp_spinbox_2.setFont(font)
        self.cp_spinbox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.cp_spinbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.cp_spinbox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.cp_spinbox_2.setMinimum(-99999.0)
        self.cp_spinbox_2.setMaximum(999999.0)
        self.cp_spinbox_2.setObjectName("cp_spinbox_2")
        self.gridLayout_5.addWidget(self.cp_spinbox_2, 7, 4, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.fluido2_page)
        self.label_22.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.gridLayout_5.addWidget(self.label_22, 7, 5, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.label_23.sizePolicy().hasHeightForWidth())
        self.label_23.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(13)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout_5.addWidget(self.label_23, 8, 0, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_21.sizePolicy().hasHeightForWidth())
        self.label_21.setSizePolicy(sizePolicy)
        self.label_21.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_5.addWidget(self.label_21, 8, 3, 1, 1)
        self.rho_spinbox_2 = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.rho_spinbox_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.rho_spinbox_2.setFont(font)
        self.rho_spinbox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.rho_spinbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.rho_spinbox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.rho_spinbox_2.setMinimum(-99999.0)
        self.rho_spinbox_2.setMaximum(999999.0)
        self.rho_spinbox_2.setObjectName("rho_spinbox_2")
        self.gridLayout_5.addWidget(self.rho_spinbox_2, 8, 4, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.fluido2_page)
        self.label_24.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.gridLayout_5.addWidget(self.label_24, 8, 5, 1, 1)
        self.fluidos_combobox_2 = QtWidgets.QComboBox(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fluidos_combobox_2.sizePolicy().hasHeightForWidth())
        self.fluidos_combobox_2.setSizePolicy(sizePolicy)
        self.fluidos_combobox_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(11)
        self.fluidos_combobox_2.setFont(font)
        self.fluidos_combobox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fluidos_combobox_2.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fluidos_combobox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fluidos_combobox_2.setInsertPolicy(QtWidgets.QComboBox.InsertAtBottom)
        self.fluidos_combobox_2.setFrame(False)
        self.fluidos_combobox_2.setModelColumn(0)
        self.fluidos_combobox_2.setObjectName("fluidos_combobox_2")
        self.fluidos_combobox_2.addItem("")
        self.fluidos_combobox_2.addItem("")
        self.fluidos_combobox_2.addItem("")
        self.fluidos_combobox_2.addItem("")
        self.fluidos_combobox_2.addItem("")
        self.gridLayout_5.addWidget(self.fluidos_combobox_2, 9, 0, 1, 2)
        self.label_29 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_29.sizePolicy().hasHeightForWidth())
        self.label_29.setSizePolicy(sizePolicy)
        self.label_29.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_29.setObjectName("label_29")
        self.gridLayout_5.addWidget(self.label_29, 9, 3, 1, 1)
        self.mi_spinbox_2 = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.mi_spinbox_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.mi_spinbox_2.setFont(font)
        self.mi_spinbox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.mi_spinbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.mi_spinbox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.mi_spinbox_2.setMinimum(-99999.0)
        self.mi_spinbox_2.setMaximum(999999.0)
        self.mi_spinbox_2.setObjectName("mi_spinbox_2")
        self.gridLayout_5.addWidget(self.mi_spinbox_2, 9, 4, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.fluido2_page)
        self.label_31.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.gridLayout_5.addWidget(self.label_31, 9, 5, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_32.sizePolicy().hasHeightForWidth())
        self.label_32.setSizePolicy(sizePolicy)
        self.label_32.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_32.setObjectName("label_32")
        self.gridLayout_5.addWidget(self.label_32, 10, 3, 1, 1)
        self.kf_spinbox_2 = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.kf_spinbox_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.kf_spinbox_2.setFont(font)
        self.kf_spinbox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.kf_spinbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.kf_spinbox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.kf_spinbox_2.setMinimum(-99999.0)
        self.kf_spinbox_2.setMaximum(999999.0)
        self.kf_spinbox_2.setObjectName("kf_spinbox_2")
        self.gridLayout_5.addWidget(self.kf_spinbox_2, 10, 4, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.fluido2_page)
        self.label_26.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.gridLayout_5.addWidget(self.label_26, 10, 5, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.fluido2_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_28.sizePolicy().hasHeightForWidth())
        self.label_28.setSizePolicy(sizePolicy)
        self.label_28.setMaximumSize(QtCore.QSize(400, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_5.addWidget(self.label_28, 11, 3, 1, 1)
        self.r_spinbox_2 = QtWidgets.QDoubleSpinBox(self.fluido2_page)
        self.r_spinbox_2.setMinimumSize(QtCore.QSize(0, 24))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.r_spinbox_2.setFont(font)
        self.r_spinbox_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(0, 100, 148);")
        self.r_spinbox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.r_spinbox_2.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.r_spinbox_2.setMinimum(-99999.0)
        self.r_spinbox_2.setMaximum(999999.0)
        self.r_spinbox_2.setObjectName("r_spinbox_2")
        self.gridLayout_5.addWidget(self.r_spinbox_2, 11, 4, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.fluido2_page)
        self.label_33.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.gridLayout_5.addWidget(self.label_33, 11, 5, 1, 1)
        self.window_frame.addWidget(self.fluido2_page)
        self.trocador_page = QtWidgets.QWidget()
        self.trocador_page.setObjectName("trocador_page")
        self.label_19 = QtWidgets.QLabel(self.trocador_page)
        self.label_19.setGeometry(QtCore.QRect(290, 180, 47, 13))
        self.label_19.setObjectName("label_19")
        self.window_frame.addWidget(self.trocador_page)
        self.resultados_page = QtWidgets.QWidget()
        self.resultados_page.setObjectName("resultados_page")
        self.label_20 = QtWidgets.QLabel(self.resultados_page)
        self.label_20.setGeometry(QtCore.QRect(280, 240, 47, 13))
        self.label_20.setObjectName("label_20")
        self.window_frame.addWidget(self.resultados_page)
        self.gridLayout_4.addWidget(self.window_frame, 1, 2, 1, 1)
        self.buttons_frame = QtWidgets.QFrame(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.buttons_frame.sizePolicy().hasHeightForWidth())
        self.buttons_frame.setSizePolicy(sizePolicy)
        self.buttons_frame.setMinimumSize(QtCore.QSize(110, 0))
        self.buttons_frame.setSizeIncrement(QtCore.QSize(1, 1))
        self.buttons_frame.setAcceptDrops(False)
        self.buttons_frame.setStyleSheet("background-color: rgb(243, 243, 243);")
        self.buttons_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.buttons_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.buttons_frame.setLineWidth(0)
        self.buttons_frame.setMidLineWidth(1)
        self.buttons_frame.setObjectName("buttons_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.buttons_frame)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout_2.setContentsMargins(1, 0, 1, 0)
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.fluido2_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fluido2_btn.sizePolicy().hasHeightForWidth())
        self.fluido2_btn.setSizePolicy(sizePolicy)
        self.fluido2_btn.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fluido2_btn.setFont(font)
        self.fluido2_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fluido2_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fluido2_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.fluido2_btn.setFlat(True)
        self.fluido2_btn.setObjectName("fluido2_btn")
        self.gridLayout.addWidget(self.fluido2_btn, 2, 0, 1, 1)
        self.fluido1_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.fluido1_btn.sizePolicy().hasHeightForWidth())
        self.fluido1_btn.setSizePolicy(sizePolicy)
        self.fluido1_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.fluido1_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.fluido1_btn.setFont(font)
        self.fluido1_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.fluido1_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.fluido1_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.fluido1_btn.setAutoFillBackground(False)
        self.fluido1_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.fluido1_btn.setCheckable(False)
        self.fluido1_btn.setChecked(False)
        self.fluido1_btn.setAutoRepeat(False)
        self.fluido1_btn.setDefault(False)
        self.fluido1_btn.setFlat(True)
        self.fluido1_btn.setObjectName("fluido1_btn")
        self.gridLayout.addWidget(self.fluido1_btn, 1, 0, 1, 1)
        self.resultados_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.resultados_btn.sizePolicy().hasHeightForWidth())
        self.resultados_btn.setSizePolicy(sizePolicy)
        self.resultados_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.resultados_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resultados_btn.setFont(font)
        self.resultados_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.resultados_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.resultados_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.resultados_btn.setFlat(True)
        self.resultados_btn.setObjectName("resultados_btn")
        self.gridLayout.addWidget(self.resultados_btn, 4, 0, 1, 1)
        self.trocador_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.trocador_btn.sizePolicy().hasHeightForWidth())
        self.trocador_btn.setSizePolicy(sizePolicy)
        self.trocador_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.trocador_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.trocador_btn.setFont(font)
        self.trocador_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.trocador_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.trocador_btn.setStyleSheet("background-color: rgb(237, 237, 237);\n"
"color: rgb(48, 143, 123);")
        self.trocador_btn.setFlat(True)
        self.trocador_btn.setObjectName("trocador_btn")
        self.gridLayout.addWidget(self.trocador_btn, 3, 0, 1, 1)
        self.projeto_btn = QtWidgets.QPushButton(self.buttons_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.projeto_btn.sizePolicy().hasHeightForWidth())
        self.projeto_btn.setSizePolicy(sizePolicy)
        self.projeto_btn.setMinimumSize(QtCore.QSize(0, 100))
        self.projeto_btn.setSizeIncrement(QtCore.QSize(0, 1))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.projeto_btn.setFont(font)
        self.projeto_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.projeto_btn.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.projeto_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.projeto_btn.setAutoFillBackground(False)
        self.projeto_btn.setStyleSheet("background-color:rgb(217, 217, 217);\n"
"color: rgb(48, 143, 123);")
        self.projeto_btn.setCheckable(False)
        self.projeto_btn.setChecked(False)
        self.projeto_btn.setAutoRepeat(False)
        self.projeto_btn.setDefault(False)
        self.projeto_btn.setFlat(True)
        self.projeto_btn.setObjectName("projeto_btn")
        self.gridLayout.addWidget(self.projeto_btn, 0, 0, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.gridLayout_4.addWidget(self.buttons_frame, 1, 0, 1, 1)
        self.toolbar = QtWidgets.QFrame(self.centralwidget)
        self.toolbar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.toolbar.setStyleSheet("background-color: rgb(48, 143, 123);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.toolbar.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.toolbar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.toolbar.setObjectName("toolbar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.toolbar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.title_label = QtWidgets.QLabel(self.toolbar)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        self.title_label.setFont(font)
        self.title_label.setAlignment(QtCore.Qt.AlignCenter)
        self.title_label.setObjectName("title_label")
        self.horizontalLayout.addWidget(self.title_label)
        self.pushButton_6 = QtWidgets.QPushButton(self.toolbar)
        self.pushButton_6.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_6.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout.addWidget(self.pushButton_6)
        self.gridLayout_4.addWidget(self.toolbar, 0, 2, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("color: rgb(48, 143, 123);")
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(2)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout_4.addWidget(self.line, 0, 1, 2, 1)
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.window_frame.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.toolBox.layout().setSpacing(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.T1_entry, self.T2_entry)
        MainWindow.setTabOrder(self.T2_entry, self.vazao_entry)
        MainWindow.setTabOrder(self.vazao_entry, self.pushButton_6)

# -----------------------------------------------
        #   Adicionando funcionalidade aos botoes
        #
        #   No primeiro bloco abaixo sao conectados os botoes a funcao oMensageiro que por sua vez faz o intermedio 
        #   GUI x funcoes
        #
        # -----------------------------------------------
    
        #Carregamento inicial

        if 1:     #Carregando fluidos pro sistema
            fluidos = Nome_fluidos()
            fluidos.insert(0, "Personalizado")
            list_fluidos = []
            for i in fluidos:
                i = i.title()
                list_fluidos.append(i)
            self.fluidos_combobox.clear()
            self.fluidos_combobox.addItems(list_fluidos)


        #self.btn_origem.clicked.connect(self.correioEnderecoOrigem)   -- SEM PARAMETROS
        #Ligacao pros botoes
        self.projeto_btn.clicked.connect(partial(self.oMensageiro, funcao=str("projetopage_clicked")))
        self.fluido1_btn.clicked.connect(partial(self.oMensageiro, funcao=str("fluido1page_clicked")))
        self.fluido2_btn.clicked.connect(partial(self.oMensageiro, funcao=str("fluido2page_clicked")))
        self.trocador_btn.clicked.connect(partial(self.oMensageiro, funcao=str("trocadorpage_clicked")))
        self.resultados_btn.clicked.connect(partial(self.oMensageiro, funcao=str("resultados_page_clicked")))

        #Combobox de fluidos
        self.fluidos_combobox.currentIndexChanged.connect(partial(self.oMensageiro, funcao=str("fluidoAtualizado")))

    def oMensageiro(self, funcao):
        #Essa funcao faz o intermedio entre bibliotecas e tela grafica

        #Trocas de tela
        if funcao == "projetopage_clicked":
            self.window_frame.setCurrentIndex(0)
            self.title_label.setText("Projeto")
        elif funcao== "fluido1page_clicked":
            self.window_frame.setCurrentIndex(1)
            self.title_label.setText("Fluido 1")
        elif funcao == "fluido2page_clicked":
            self.window_frame.setCurrentIndex(2)
            self.title_label.setText("Fluido 2")
        elif funcao == "trocadorpage_clicked":
            self.window_frame.setCurrentIndex(3)
            self.title_label.setText("Trocador")
        elif funcao == "resultados_page_clicked":
            self.window_frame.setCurrentIndex(4)
            self.title_label.setText("Resultados")

        #Carrega propriedades do fluido
        elif funcao == "fluidoAtualizado":
            fluido = self.fluidos_combobox.currentText()
            T1 = float(self.T1_entry.text())
            T2 = float(self.T2_entry.text())
            [rho,cp,kf,mi,pr] = tabela_fluidos(fluido, T1, T2)
            self.cp_spinbox.setValue(cp)
            self.rho_spinbox.setValue(rho)
            self.mi_spinbox.setValue(mi)
            self.kf_spinbox.setValue(kf)
            self.r_spinbox.setValue(0)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "HH:mm:ss"))
        self.mainTitle_label.setText(_translate("MainWindow", "STC"))
        self.label_17.setText(_translate("MainWindow", "Simulador de trocador de calor"))
        self.radioButton.setText(_translate("MainWindow", "Trocador de placas"))
        self.radioButton_3.setText(_translate("MainWindow", "Bitubular"))
        self.radioButton_2.setText(_translate("MainWindow", "Casco e tubo"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("MainWindow", "Novo projeto"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("MainWindow", "Carregar projeto"))
        self.label_34.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/logo.jpg\"/>STC EQI016 - Engenharia Química - Universidade Federal de Itajubá (2019) <img src=\"images/unifei_logo.png\"/></p></body></html>"))
        self.label_11.setText(_translate("MainWindow", "Fator de incrustação (R)"))
        self.label_7.setText(_translate("MainWindow", "Calor específico (Cp)"))
        self.fluidos_combobox.setItemText(0, _translate("MainWindow", "Personalizado"))
        self.fluidos_combobox.setItemText(1, _translate("MainWindow", "Água"))
        self.fluidos_combobox.setItemText(2, _translate("MainWindow", "Amonia"))
        self.fluidos_combobox.setItemText(3, _translate("MainWindow", "Benzeno"))
        self.fluidos_combobox.setItemText(4, _translate("MainWindow", "Tolueno"))
        self.label_6.setText(_translate("MainWindow", "Selecionar fluido"))
        self.comboBox.setItemText(0, _translate("MainWindow", "ºC"))
        self.comboBox.setItemText(1, _translate("MainWindow", "K"))
        self.comboBox.setItemText(2, _translate("MainWindow", "ºF"))
        self.comboBox.setItemText(3, _translate("MainWindow", "R"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "kg/h"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "g/s"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "L/s"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "m³/h"))
        self.label_4.setText(_translate("MainWindow", "Temperatura de saída do fluido"))
        self.label_5.setText(_translate("MainWindow", "Vazão do fluido"))
        self.label_2.setText(_translate("MainWindow", "Temperatura de entrada do fluido"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "ºC"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "K"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "ºF"))
        self.comboBox_2.setItemText(3, _translate("MainWindow", "R"))
        self.label_8.setText(_translate("MainWindow", "Viscosidade dinâmica (μ)"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/Plate_heat_exchanger.jpg\"/></p></body></html>"))
        self.label_14.setText(_translate("MainWindow", "[μPa.s]"))
        self.label_16.setText(_translate("MainWindow", "[(s.m².K)/J]"))
        self.label_13.setText(_translate("MainWindow", "[kg/m³]"))
        self.label_12.setText(_translate("MainWindow", "[kJ/(kg.K)]"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p>Massa específica (ρ)</p></body></html>"))
        self.label_15.setText(_translate("MainWindow", "[mW/(m.K)]"))
        self.label_10.setText(_translate("MainWindow", "Condutividade térmica (k)"))
        self.label_3.setText(_translate("MainWindow", "Temperatura de entrada do fluido"))
        self.label_30.setText(_translate("MainWindow", "<html><head/><body><p><img src=\"images/Plate_heat_exchanger.jpg\"/></p></body></html>"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "ºC"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "K"))
        self.comboBox_5.setItemText(2, _translate("MainWindow", "ºF"))
        self.comboBox_5.setItemText(3, _translate("MainWindow", "R"))
        self.label_18.setText(_translate("MainWindow", "Temperatura de saída do fluido"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "ºC"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "K"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "ºF"))
        self.comboBox_4.setItemText(3, _translate("MainWindow", "R"))
        self.label_27.setText(_translate("MainWindow", "Vazão do fluido"))
        self.comboBox_6.setItemText(0, _translate("MainWindow", "kg/h"))
        self.comboBox_6.setItemText(1, _translate("MainWindow", "g/s"))
        self.comboBox_6.setItemText(2, _translate("MainWindow", "L/s"))
        self.comboBox_6.setItemText(3, _translate("MainWindow", "m³/h"))
        self.label_25.setText(_translate("MainWindow", "Calor específico (Cp)"))
        self.label_22.setText(_translate("MainWindow", "[kJ/(kg.K)]"))
        self.label_23.setText(_translate("MainWindow", "Selecionar fluido"))
        self.label_21.setText(_translate("MainWindow", "<html><head/><body><p>Massa específica (ρ)</p></body></html>"))
        self.label_24.setText(_translate("MainWindow", "[kg/m³]"))
        self.fluidos_combobox_2.setItemText(0, _translate("MainWindow", "Personalizado"))
        self.fluidos_combobox_2.setItemText(1, _translate("MainWindow", "Água"))
        self.fluidos_combobox_2.setItemText(2, _translate("MainWindow", "Amonia"))
        self.fluidos_combobox_2.setItemText(3, _translate("MainWindow", "Benzeno"))
        self.fluidos_combobox_2.setItemText(4, _translate("MainWindow", "Tolueno"))
        self.label_29.setText(_translate("MainWindow", "Viscosidade dinâmica (μ)"))
        self.label_31.setText(_translate("MainWindow", "[μPa.s]"))
        self.label_32.setText(_translate("MainWindow", "Condutividade térmica (k)"))
        self.label_26.setText(_translate("MainWindow", "[mW/(m.K)]"))
        self.label_28.setText(_translate("MainWindow", "Fator de incrustação (R)"))
        self.label_33.setText(_translate("MainWindow", "[(s.m².K)/J]"))
        self.label_19.setText(_translate("MainWindow", "Trocador"))
        self.label_20.setText(_translate("MainWindow", "Resultados"))
        self.fluido2_btn.setText(_translate("MainWindow", "Fluido 2"))
        self.fluido2_btn.setShortcut(_translate("MainWindow", "3"))
        self.fluido1_btn.setText(_translate("MainWindow", "Fluido 1"))
        self.fluido1_btn.setShortcut(_translate("MainWindow", "2"))
        self.resultados_btn.setText(_translate("MainWindow", "Resultados"))
        self.resultados_btn.setShortcut(_translate("MainWindow", "5"))
        self.trocador_btn.setText(_translate("MainWindow", "Trocador"))
        self.trocador_btn.setShortcut(_translate("MainWindow", "4"))
        self.projeto_btn.setText(_translate("MainWindow", "Projeto"))
        self.projeto_btn.setShortcut(_translate("MainWindow", "1"))
        self.title_label.setText(_translate("MainWindow", "title"))
        self.pushButton_6.setText(_translate("MainWindow", "Calculate"))

#import images_rc

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

